server:
  port: 8100

spring:
  application:
    name: producer-service

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

  cloud:
    stream:
      #将交换机和队列绑定到了通道output上面
      bindings:
        output:
          destination: sendChannel
          group: queue-1
#          binder: rabbit
#        input:
#          destination: ackChannel
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8300/eureka


