server:
  port: 8888
spring:
  application:
    name: gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: product_router
#          uri: lb://producer-service
#          predicates:
#            - Path= /producer-service/**
#          filters:
#            - StripPrefix=1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8300/eureka
