server:
  port: 8053

spring:
  application:
    name: nacos-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql:///test?useUnicode=true&autoReconnect=true&failOverReadOnly=false&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: 1ms
        min-idle: 1
        max-idle: 8
    timeout: 50000ms
    database: 0

jackson:
  property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES  #驼峰转下划线

mybatis-plus:
  configuration:
    cache-enabled: true  #开启缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #